=== DylanG129/assignment-1--databases--cs-365--fall-2023/xml/dtd/student.dtd
<!--
    The root element: student-archive

    The student-archive container (root) element must have one or more
    student elements.
-->
<!ELEMENT student-archive (student)+>
<!-- 
The student container element must contain one name container, one personal-info
container, one school-info containor and one date container.
-->
<!ELEMENT student (name,personal-info,school-info,date)>
<!-- 
The name container element must contain one firstname, one middlename, one lastname
and one preferredname.
-->
<!ELEMENT name (firstname,middlename,lastname,preferredname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT middlename (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT preferredname (#PCDATA)>
<!-- 
The personal-info container element must contain one email and one phone.
-->
<!ELEMENT personal-info (email,phone)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!-- 
The school-info container element must contain one student-id, one major, one minor,
one gpa and one advisor.
-->
<!ELEMENT school-info (student-id,major,minor,gpa,advisor)>
<!ELEMENT student-id (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!-- 
The date container element must contain one date-of-enrollment and one
graduation. 
-->
<!ELEMENT date (date-of-enrollment,graduation)>
<!ELEMENT date-of-enrollment (#PCDATA)>
<!ELEMENT graduation (#PCDATA)>

<!ATTLIST student
        num CDATA #REQUIRED>
<!-- 
attributed to the school-info container is status and grade.

status must be either full-time, part-time, graduated or withdrawn.

grade must be either first-year, second-year, third-year or fourth-year.
-->
<!ATTLIST school-info
        status (full-time|part-time|graduated|withdrawn) #REQUIRED>

<!ATTLIST school-info
        grade (first-year|second-year|third-year|fourth-year) #REQUIRED>

=== DylanG129/assignment-1--databases--cs-365--fall-2023/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="..\xml\css\style.css"?>
<!DOCTYPE student-archive SYSTEM "..\xml\dtd\student.dtd" [
<!ENTITY pop "University">
]>
<student-archive>
    <student num = "1">
        <name>
            <firstname>Gordon</firstname>
            <middlename>Matthew</middlename>
            <lastname>Sumner</lastname>
            <preferredname>Sting</preferredname>
        </name>
        <personal-info>
            <email>sting@thepolice.com</email>
            <phone>212.123.4567</phone>
        </personal-info>
        <school-info status="full-time" grade="first-year">
            <student-id>1234567</student-id>
            <major>Music</major>
            <minor>English</minor>
            <gpa>4.0</gpa>
            <advisor>Andy Summers</advisor>
        </school-info>
        <date>
            <date-of-enrollment>08-25-1969</date-of-enrollment>
            <graduation>05-01-1973</graduation>
        </date>
    </student>

    <student num="2">
        <name>
            <firstname>Kim</firstname>
            <middlename></middlename>
            <lastname>Thayil</lastname>
            <preferredname>n/a</preferredname>
        </name>
        <personal-info>
            <email>kim@soundgarden</email>
            <phone>206.123.4567</phone>
        </personal-info>
        <school-info status="full-time" grade="second-year">
            <student-id>567890</student-id>
            <major>Philosophy</major>
            <minor>Music</minor>
            <gpa>3.0</gpa>
            <advisor>Chris Cornell</advisor>
        </school-info>
        <date>
            <date-of-enrollment>08-25-1983</date-of-enrollment>
            <graduation>05-01-1982</graduation>
        </date>
    </student>
</student-archive>
